PLUGINS = \
{'_failed': [],
 'apps': {'av': {'mcafee': {'class': 'McAfeePlugin',
                            'exports': ['msc'],
                            'fullname': 'dissect.target.plugins.apps.av.mcafee.McAfeePlugin',
                            'functions': ['msc'],
                            'module': 'apps.av.mcafee',
                            'namespace': 'mcafee'},
                 'trendmicro': {'class': 'TrendMicroPlugin',
                                'exports': ['wffirewall', 'wflogs'],
                                'fullname': 'dissect.target.plugins.apps.av.trendmicro.TrendMicroPlugin',
                                'functions': ['wffirewall', 'wflogs'],
                                'module': 'apps.av.trendmicro',
                                'namespace': 'trendmicro'}},
          'containers': {'docker': {'class': 'DockerPlugin',
                                    'exports': ['containers', 'images'],
                                    'fullname': 'dissect.target.plugins.apps.containers.docker.DockerPlugin',
                                    'functions': ['containers', 'images'],
                                    'module': 'apps.containers.docker',
                                    'namespace': 'docker'}},
          'remoteaccess': {'anydesk': {'class': 'AnydeskPlugin',
                                       'exports': ['remoteaccess'],
                                       'fullname': 'dissect.target.plugins.apps.remoteaccess.anydesk.AnydeskPlugin',
                                       'functions': ['remoteaccess'],
                                       'module': 'apps.remoteaccess.anydesk',
                                       'namespace': 'anydesk'},
                           'remoteaccess': {'class': 'RemoteAccessPlugin',
                                            'exports': ['remoteaccess'],
                                            'fullname': 'dissect.target.plugins.apps.remoteaccess.remoteaccess.RemoteAccessPlugin',
                                            'functions': ['remoteaccess'],
                                            'module': 'apps.remoteaccess.remoteaccess',
                                            'namespace': 'remoteaccess'},
                           'teamviewer': {'class': 'TeamviewerPlugin',
                                          'exports': ['remoteaccess'],
                                          'fullname': 'dissect.target.plugins.apps.remoteaccess.teamviewer.TeamviewerPlugin',
                                          'functions': ['remoteaccess'],
                                          'module': 'apps.remoteaccess.teamviewer',
                                          'namespace': 'teamviewer'}},
          'vpns': {'wireguard': {'class': 'WireGuardPlugin',
                                 'exports': ['config'],
                                 'fullname': 'dissect.target.plugins.apps.vpns.wireguard.WireGuardPlugin',
                                 'functions': ['config'],
                                 'module': 'apps.vpns.wireguard',
                                 'namespace': 'wireguard'}},
          'webservers': {'apache': {'class': 'ApachePlugin',
                                    'exports': ['access'],
                                    'fullname': 'dissect.target.plugins.apps.webservers.apache.ApachePlugin',
                                    'functions': ['access', 'get_log_paths'],
                                    'module': 'apps.webservers.apache',
                                    'namespace': 'apache'},
                         'caddy': {'class': 'CaddyPlugin',
                                   'exports': ['access'],
                                   'fullname': 'dissect.target.plugins.apps.webservers.caddy.CaddyPlugin',
                                   'functions': ['access', 'get_log_paths'],
                                   'module': 'apps.webservers.caddy',
                                   'namespace': 'caddy'},
                         'iis': {'class': 'IISLogsPlugin',
                                 'exports': ['access', 'logs'],
                                 'fullname': 'dissect.target.plugins.apps.webservers.iis.IISLogsPlugin',
                                 'functions': ['access',
                                               'get_log_dirs',
                                               'iter_log_format_path_pairs',
                                               'iter_log_paths',
                                               'logs',
                                               'parse_iis_format_log',
                                               'parse_w3c_format_log'],
                                 'module': 'apps.webservers.iis',
                                 'namespace': 'iis'},
                         'nginx': {'class': 'NginxPlugin',
                                   'exports': ['access'],
                                   'fullname': 'dissect.target.plugins.apps.webservers.nginx.NginxPlugin',
                                   'functions': ['access', 'get_log_paths'],
                                   'module': 'apps.webservers.nginx',
                                   'namespace': 'nginx'},
                         'webservers': {'class': 'WebserverPlugin',
                                        'exports': ['access', 'logs'],
                                        'fullname': 'dissect.target.plugins.apps.webservers.webservers.WebserverPlugin',
                                        'functions': ['access', 'logs'],
                                        'module': 'apps.webservers.webservers',
                                        'namespace': 'webserver'}}},
 'browsers': {'browser': {'class': 'BrowserPlugin',
                          'exports': ['downloads', 'history'],
                          'fullname': 'dissect.target.plugins.browsers.browser.BrowserPlugin',
                          'functions': ['downloads', 'history'],
                          'module': 'browsers.browser',
                          'namespace': 'browser'},
              'chrome': {'class': 'ChromePlugin',
                         'exports': ['downloads', 'history'],
                         'fullname': 'dissect.target.plugins.browsers.chrome.ChromePlugin',
                         'functions': ['downloads', 'history'],
                         'module': 'browsers.chrome',
                         'namespace': 'chrome'},
              'chromium': {'class': 'ChromiumPlugin',
                           'exports': ['downloads', 'history'],
                           'fullname': 'dissect.target.plugins.browsers.chromium.ChromiumPlugin',
                           'functions': ['downloads', 'history'],
                           'module': 'browsers.chromium',
                           'namespace': 'chromium'},
              'edge': {'class': 'EdgePlugin',
                       'exports': ['downloads', 'history'],
                       'fullname': 'dissect.target.plugins.browsers.edge.EdgePlugin',
                       'functions': ['downloads', 'history'],
                       'module': 'browsers.edge',
                       'namespace': 'edge'},
              'firefox': {'class': 'FirefoxPlugin',
                          'exports': ['downloads', 'history'],
                          'fullname': 'dissect.target.plugins.browsers.firefox.FirefoxPlugin',
                          'functions': ['downloads', 'history'],
                          'module': 'browsers.firefox',
                          'namespace': 'firefox'},
              'iexplore': {'class': 'InternetExplorerPlugin',
                           'exports': ['downloads', 'history'],
                           'fullname': 'dissect.target.plugins.browsers.iexplore.InternetExplorerPlugin',
                           'functions': ['downloads',
                                         'history',
                                         'is_compatible'],
                           'module': 'browsers.iexplore',
                           'namespace': 'iexplore'}},
 'child': {'esxi': {'_child': [{'class': 'ESXiChildTargetPlugin',
                                'exports': ['get_all_records'],
                                'fullname': 'dissect.target.plugins.child.esxi.ESXiChildTargetPlugin',
                                'functions': ['get_all_records'],
                                'module': 'child.esxi',
                                'namespace': None}]},
           'hyperv': {'_child': [{'class': 'HyperVChildTargetPlugin',
                                  'exports': ['get_all_records'],
                                  'fullname': 'dissect.target.plugins.child.hyperv.HyperVChildTargetPlugin',
                                  'functions': ['get_all_records'],
                                  'module': 'child.hyperv',
                                  'namespace': None}]},
           'virtuozzo': {'_child': [{'class': 'VirtuozzoChildTargetPlugin',
                                     'exports': ['get_all_records'],
                                     'fullname': 'dissect.target.plugins.child.virtuozzo.VirtuozzoChildTargetPlugin',
                                     'functions': ['get_all_records'],
                                     'module': 'child.virtuozzo',
                                     'namespace': None}]},
           'vmware_workstation': {'_child': [{'class': 'WorkstationChildTargetPlugin',
                                              'exports': ['get_all_records'],
                                              'fullname': 'dissect.target.plugins.child.vmware_workstation.WorkstationChildTargetPlugin',
                                              'functions': ['get_all_records'],
                                              'module': 'child.vmware_workstation',
                                              'namespace': None}]},
           'wsl': {'_child': [{'class': 'WSLChildTargetPlugin',
                               'exports': ['get_all_records'],
                               'fullname': 'dissect.target.plugins.child.wsl.WSLChildTargetPlugin',
                               'functions': ['get_all_records'],
                               'module': 'child.wsl',
                               'namespace': None}]}},
 'dissect': {'target': {'plugin': {'class': 'InternalPlugin',
                                   'exports': [],
                                   'fullname': 'dissect.target.plugin.InternalPlugin',
                                   'functions': [],
                                   'module': 'dissect.target.plugin',
                                   'namespace': None}}},
 'filesystem': {'acquire_handles': {'class': 'OpenHandlesPlugin',
                                    'exports': ['acquire_handles'],
                                    'fullname': 'dissect.target.plugins.filesystem.acquire_handles.OpenHandlesPlugin',
                                    'functions': ['acquire_handles'],
                                    'module': 'filesystem.acquire_handles',
                                    'namespace': None},
                'acquire_hash': {'class': 'AcquireHashPlugin',
                                 'exports': ['acquire_hashes'],
                                 'fullname': 'dissect.target.plugins.filesystem.acquire_hash.AcquireHashPlugin',
                                 'functions': ['acquire_hashes'],
                                 'module': 'filesystem.acquire_hash',
                                 'namespace': None},
                'icat': {'class': 'ICatPlugin',
                         'exports': ['icat'],
                         'fullname': 'dissect.target.plugins.filesystem.icat.ICatPlugin',
                         'functions': ['icat'],
                         'module': 'filesystem.icat',
                         'namespace': None},
                'ntfs': {'mft': {'class': 'MftPlugin',
                                 'exports': ['mft'],
                                 'fullname': 'dissect.target.plugins.filesystem.ntfs.mft.MftPlugin',
                                 'functions': ['mft'],
                                 'module': 'filesystem.ntfs.mft',
                                 'namespace': None},
                         'mft_timeline': {'class': 'MftTimelinePlugin',
                                          'exports': ['mft_timeline'],
                                          'fullname': 'dissect.target.plugins.filesystem.ntfs.mft_timeline.MftTimelinePlugin',
                                          'functions': ['mft_timeline'],
                                          'module': 'filesystem.ntfs.mft_timeline',
                                          'namespace': None},
                         'usnjrnl': {'class': 'UsnjrnlPlugin',
                                     'exports': ['usnjrnl'],
                                     'fullname': 'dissect.target.plugins.filesystem.ntfs.usnjrnl.UsnjrnlPlugin',
                                     'functions': ['usnjrnl'],
                                     'module': 'filesystem.ntfs.usnjrnl',
                                     'namespace': None}},
                'resolver': {'class': 'ResolverPlugin',
                             'exports': [],
                             'fullname': 'dissect.target.plugins.filesystem.resolver.ResolverPlugin',
                             'functions': ['resolve'],
                             'module': 'filesystem.resolver',
                             'namespace': None},
                'unix': {'capability': {'class': 'CapabilityPlugin',
                                        'exports': ['capability_binaries'],
                                        'fullname': 'dissect.target.plugins.filesystem.unix.capability.CapabilityPlugin',
                                        'functions': ['capability_binaries'],
                                        'module': 'filesystem.unix.capability',
                                        'namespace': None},
                         'suid': {'class': 'SuidPlugin',
                                  'exports': ['suid_binaries'],
                                  'fullname': 'dissect.target.plugins.filesystem.unix.suid.SuidPlugin',
                                  'functions': ['suid_binaries'],
                                  'module': 'filesystem.unix.suid',
                                  'namespace': None}},
                'walkfs': {'class': 'WalkFSPlugin',
                           'exports': ['walkfs'],
                           'fullname': 'dissect.target.plugins.filesystem.walkfs.WalkFSPlugin',
                           'functions': ['walkfs', 'walkfs_ext'],
                           'module': 'filesystem.walkfs',
                           'namespace': None},
                'yara': {'class': 'YaraPlugin',
                         'exports': ['yara'],
                         'fullname': 'dissect.target.plugins.filesystem.yara.YaraPlugin',
                         'functions': ['yara'],
                         'module': 'filesystem.yara',
                         'namespace': None}},
 'general': {'default': {'_os': [{'class': 'DefaultPlugin',
                                  'exports': ['get_all_records',
                                              'hostname',
                                              'ips',
                                              'os',
                                              'users',
                                              'version'],
                                  'fullname': 'dissect.target.plugins.general.default.DefaultPlugin',
                                  'functions': ['get_all_records',
                                                'hostname',
                                                'ips',
                                                'os',
                                                'users',
                                                'version'],
                                  'module': 'general.default',
                                  'namespace': None}]},
             'example': {'class': 'ExamplePlugin',
                         'exports': ['example',
                                     'example_none',
                                     'example_record',
                                     'example_user_registry_record',
                                     'example_yield'],
                         'fullname': 'dissect.target.plugins.general.example.ExamplePlugin',
                         'functions': ['example',
                                       'example_internal',
                                       'example_none',
                                       'example_record',
                                       'example_user_registry_record',
                                       'example_yield',
                                       'is_compatible'],
                         'module': 'general.example',
                         'namespace': None},
             'loaders': {'class': 'LoaderListPlugin',
                         'exports': ['loaders'],
                         'fullname': 'dissect.target.plugins.general.loaders.LoaderListPlugin',
                         'functions': ['is_compatible', 'loaders'],
                         'module': 'general.loaders',
                         'namespace': None},
             'plugins': {'class': 'PluginListPlugin',
                         'exports': ['plugins'],
                         'fullname': 'dissect.target.plugins.general.plugins.PluginListPlugin',
                         'functions': ['is_compatible', 'plugins'],
                         'module': 'general.plugins',
                         'namespace': None},
             'scrape': {'class': 'ScrapePlugin',
                        'exports': [],
                        'fullname': 'dissect.target.plugins.general.scrape.ScrapePlugin',
                        'functions': ['find_needle_chunks',
                                      'find_needles',
                                      'is_compatible',
                                      'scrape_chunks',
                                      'scrape_chunks_from_disks',
                                      'scrape_needles_from_disks'],
                        'module': 'general.scrape',
                        'namespace': 'scrape'},
             'users': {'class': 'UsersPlugin',
                       'exports': ['get_all_records'],
                       'fullname': 'dissect.target.plugins.general.users.UsersPlugin',
                       'functions': ['all',
                                     'all_with_home',
                                     'check_compatible',
                                     'find',
                                     'get',
                                     'get_all_records',
                                     'get_all_records',
                                     'is_compatible'],
                       'module': 'general.users',
                       'namespace': 'user_details'}},
 'os': {'unix': {'_os': [{'class': 'UnixPlugin',
                          'exports': ['architecture',
                                      'domain',
                                      'get_all_records',
                                      'hostname',
                                      'ips',
                                      'os',
                                      'users',
                                      'version'],
                          'fullname': 'dissect.target.plugins.os.unix._os.UnixPlugin',
                          'functions': ['architecture',
                                        'domain',
                                        'get_all_records',
                                        'hostname',
                                        'ips',
                                        'is_compatible',
                                        'os',
                                        'users',
                                        'version'],
                          'module': 'os.unix._os',
                          'namespace': None}],
                 'bsd': {'_os': [{'class': 'BsdPlugin',
                                  'exports': ['architecture',
                                              'domain',
                                              'get_all_records',
                                              'hostname',
                                              'ips',
                                              'os',
                                              'users',
                                              'version'],
                                  'fullname': 'dissect.target.plugins.os.unix.bsd._os.BsdPlugin',
                                  'functions': ['architecture',
                                                'domain',
                                                'get_all_records',
                                                'hostname',
                                                'ips',
                                                'is_compatible',
                                                'os',
                                                'users',
                                                'version'],
                                  'module': 'os.unix.bsd._os',
                                  'namespace': None}],
                         'freebsd': {'_os': [{'class': 'FreeBsdPlugin',
                                              'exports': ['architecture',
                                                          'domain',
                                                          'get_all_records',
                                                          'hostname',
                                                          'ips',
                                                          'os',
                                                          'users',
                                                          'version'],
                                              'fullname': 'dissect.target.plugins.os.unix.bsd.freebsd._os.FreeBsdPlugin',
                                              'functions': ['architecture',
                                                            'domain',
                                                            'get_all_records',
                                                            'hostname',
                                                            'ips',
                                                            'is_compatible',
                                                            'os',
                                                            'users',
                                                            'version'],
                                              'module': 'os.unix.bsd.freebsd._os',
                                              'namespace': None}]},
                         'ios': {'_os': [{'class': 'IOSPlugin',
                                          'exports': ['architecture',
                                                      'domain',
                                                      'get_all_records',
                                                      'hostname',
                                                      'ips',
                                                      'os',
                                                      'users',
                                                      'version'],
                                          'fullname': 'dissect.target.plugins.os.unix.bsd.ios._os.IOSPlugin',
                                          'functions': ['architecture',
                                                        'domain',
                                                        'get_all_records',
                                                        'hostname',
                                                        'ips',
                                                        'is_compatible',
                                                        'os',
                                                        'users',
                                                        'version'],
                                          'module': 'os.unix.bsd.ios._os',
                                          'namespace': None}]},
                         'openbsd': {'_os': [{'class': 'OpenBsdPlugin',
                                              'exports': ['architecture',
                                                          'domain',
                                                          'get_all_records',
                                                          'hostname',
                                                          'ips',
                                                          'os',
                                                          'users',
                                                          'version'],
                                              'fullname': 'dissect.target.plugins.os.unix.bsd.openbsd._os.OpenBsdPlugin',
                                              'functions': ['architecture',
                                                            'domain',
                                                            'get_all_records',
                                                            'hostname',
                                                            'ips',
                                                            'is_compatible',
                                                            'os',
                                                            'users',
                                                            'version'],
                                              'module': 'os.unix.bsd.openbsd._os',
                                              'namespace': None}]},
                         'osx': {'_os': [{'class': 'MacPlugin',
                                          'exports': ['architecture',
                                                      'domain',
                                                      'get_all_records',
                                                      'hostname',
                                                      'ips',
                                                      'os',
                                                      'users',
                                                      'version'],
                                          'fullname': 'dissect.target.plugins.os.unix.bsd.osx._os.MacPlugin',
                                          'functions': ['architecture',
                                                        'domain',
                                                        'get_all_records',
                                                        'hostname',
                                                        'ips',
                                                        'is_compatible',
                                                        'os',
                                                        'users',
                                                        'version'],
                                          'module': 'os.unix.bsd.osx._os',
                                          'namespace': None}]}},
                 'cronjobs': {'class': 'CronjobPlugin',
                              'exports': ['cronjobs'],
                              'fullname': 'dissect.target.plugins.os.unix.cronjobs.CronjobPlugin',
                              'functions': ['cronjobs', 'is_compatible'],
                              'module': 'os.unix.cronjobs',
                              'namespace': None},
                 'datetime': {'class': 'DateTimePlugin',
                              'exports': [],
                              'fullname': 'dissect.target.plugins.os.unix.datetime.DateTimePlugin',
                              'functions': ['is_compatible',
                                            'local',
                                            'to_utc',
                                            'tz',
                                            'tzinfo'],
                              'module': 'os.unix.datetime',
                              'namespace': 'datetime'},
                 'generic': {'class': 'GenericPlugin',
                             'exports': ['activity', 'install_date'],
                             'fullname': 'dissect.target.plugins.os.unix.generic.GenericPlugin',
                             'functions': ['activity',
                                           'install_date',
                                           'is_compatible'],
                             'module': 'os.unix.generic',
                             'namespace': None},
                 'history': {'class': 'CommandHistoryPlugin',
                             'exports': ['bashhistory', 'commandhistory'],
                             'fullname': 'dissect.target.plugins.os.unix.history.CommandHistoryPlugin',
                             'functions': ['bashhistory',
                                           'commandhistory',
                                           'is_compatible',
                                           'parse_bash_history',
                                           'parse_zsh_history'],
                             'module': 'os.unix.history',
                             'namespace': None},
                 'linux': {'_os': [{'class': 'LinuxPlugin',
                                    'exports': ['architecture',
                                                'dhcp',
                                                'dns',
                                                'domain',
                                                'gateway',
                                                'get_all_records',
                                                'hostname',
                                                'interface',
                                                'ips',
                                                'netmask',
                                                'os',
                                                'users',
                                                'version'],
                                    'fullname': 'dissect.target.plugins.os.unix.linux._os.LinuxPlugin',
                                    'functions': ['architecture',
                                                  'dhcp',
                                                  'dns',
                                                  'domain',
                                                  'gateway',
                                                  'get_all_records',
                                                  'hostname',
                                                  'interface',
                                                  'ips',
                                                  'is_compatible',
                                                  'netmask',
                                                  'os',
                                                  'users',
                                                  'version'],
                                    'module': 'os.unix.linux._os',
                                    'namespace': None}],
                           'android': {'_os': [{'class': 'AndroidPlugin',
                                                'exports': ['get_all_records',
                                                            'hostname',
                                                            'ips',
                                                            'os',
                                                            'version'],
                                                'fullname': 'dissect.target.plugins.os.unix.linux.android._os.AndroidPlugin',
                                                'functions': ['get_all_records',
                                                              'hostname',
                                                              'ips',
                                                              'is_compatible',
                                                              'os',
                                                              'version'],
                                                'module': 'os.unix.linux.android._os',
                                                'namespace': None}]},
                           'debian': {'_os': [{'class': 'DebianPlugin',
                                               'exports': ['architecture',
                                                           'dhcp',
                                                           'dns',
                                                           'domain',
                                                           'gateway',
                                                           'get_all_records',
                                                           'hostname',
                                                           'interface',
                                                           'ips',
                                                           'netmask',
                                                           'os',
                                                           'users',
                                                           'version'],
                                               'fullname': 'dissect.target.plugins.os.unix.linux.debian._os.DebianPlugin',
                                               'functions': ['architecture',
                                                             'dhcp',
                                                             'dns',
                                                             'domain',
                                                             'gateway',
                                                             'get_all_records',
                                                             'hostname',
                                                             'interface',
                                                             'ips',
                                                             'is_compatible',
                                                             'netmask',
                                                             'os',
                                                             'users',
                                                             'version'],
                                               'module': 'os.unix.linux.debian._os',
                                               'namespace': None}],
                                      'apt': {'class': 'AptPlugin',
                                              'exports': ['logs'],
                                              'fullname': 'dissect.target.plugins.os.unix.linux.debian.apt.AptPlugin',
                                              'functions': ['is_compatible',
                                                            'logs'],
                                              'module': 'os.unix.linux.debian.apt',
                                              'namespace': 'apt'},
                                      'dpkg': {'class': 'DpkgPlugin',
                                               'exports': ['log', 'status'],
                                               'fullname': 'dissect.target.plugins.os.unix.linux.debian.dpkg.DpkgPlugin',
                                               'functions': ['is_compatible',
                                                             'log',
                                                             'status'],
                                               'module': 'os.unix.linux.debian.dpkg',
                                               'namespace': 'dpkg'},
                                      'vyos': {'_os': [{'class': 'VyosPlugin',
                                                        'exports': ['architecture',
                                                                    'dhcp',
                                                                    'dns',
                                                                    'domain',
                                                                    'gateway',
                                                                    'get_all_records',
                                                                    'hostname',
                                                                    'interface',
                                                                    'ips',
                                                                    'netmask',
                                                                    'os',
                                                                    'users',
                                                                    'version'],
                                                        'fullname': 'dissect.target.plugins.os.unix.linux.debian.vyos._os.VyosPlugin',
                                                        'functions': ['architecture',
                                                                      'dhcp',
                                                                      'dns',
                                                                      'domain',
                                                                      'gateway',
                                                                      'get_all_records',
                                                                      'hostname',
                                                                      'interface',
                                                                      'ips',
                                                                      'is_compatible',
                                                                      'netmask',
                                                                      'os',
                                                                      'users',
                                                                      'version'],
                                                        'module': 'os.unix.linux.debian.vyos._os',
                                                        'namespace': None}]}},
                           'esxi': {'_os': [{'class': 'ESXiPlugin',
                                             'exports': ['architecture',
                                                         'dhcp',
                                                         'dns',
                                                         'domain',
                                                         'esxconf',
                                                         'gateway',
                                                         'get_all_records',
                                                         'hostname',
                                                         'interface',
                                                         'ips',
                                                         'netmask',
                                                         'os',
                                                         'users',
                                                         'version',
                                                         'vm_inventory'],
                                             'fullname': 'dissect.target.plugins.os.unix.linux.esxi._os.ESXiPlugin',
                                             'functions': ['architecture',
                                                           'configstore',
                                                           'dhcp',
                                                           'dns',
                                                           'domain',
                                                           'esxconf',
                                                           'gateway',
                                                           'get_all_records',
                                                           'hostname',
                                                           'interface',
                                                           'ips',
                                                           'is_compatible',
                                                           'netmask',
                                                           'os',
                                                           'users',
                                                           'version',
                                                           'vm_inventory'],
                                             'module': 'os.unix.linux.esxi._os',
                                             'namespace': None}]},
                           'fortigate': {'_os': [{'class': 'FortigatePlugin',
                                                  'exports': ['architecture',
                                                              'dhcp',
                                                              'dns',
                                                              'domain',
                                                              'gateway',
                                                              'get_all_records',
                                                              'hostname',
                                                              'interface',
                                                              'ips',
                                                              'netmask',
                                                              'os',
                                                              'users',
                                                              'version'],
                                                  'fullname': 'dissect.target.plugins.os.unix.linux.fortigate._os.FortigatePlugin',
                                                  'functions': ['architecture',
                                                                'dhcp',
                                                                'dns',
                                                                'domain',
                                                                'gateway',
                                                                'get_all_records',
                                                                'hostname',
                                                                'interface',
                                                                'ips',
                                                                'is_compatible',
                                                                'netmask',
                                                                'os',
                                                                'users',
                                                                'version'],
                                                  'module': 'os.unix.linux.fortigate._os',
                                                  'namespace': None}]},
                           'redhat': {'_os': [{'class': 'RedHat',
                                               'exports': ['architecture',
                                                           'dhcp',
                                                           'dns',
                                                           'domain',
                                                           'gateway',
                                                           'get_all_records',
                                                           'hostname',
                                                           'interface',
                                                           'ips',
                                                           'netmask',
                                                           'os',
                                                           'users',
                                                           'version'],
                                               'fullname': 'dissect.target.plugins.os.unix.linux.redhat._os.RedHat',
                                               'functions': ['architecture',
                                                             'dhcp',
                                                             'dns',
                                                             'domain',
                                                             'gateway',
                                                             'get_all_records',
                                                             'hostname',
                                                             'interface',
                                                             'ips',
                                                             'is_compatible',
                                                             'netmask',
                                                             'os',
                                                             'users',
                                                             'version'],
                                               'module': 'os.unix.linux.redhat._os',
                                               'namespace': None}],
                                      'yum': {'class': 'YumPlugin',
                                              'exports': ['logs'],
                                              'fullname': 'dissect.target.plugins.os.unix.linux.redhat.yum.YumPlugin',
                                              'functions': ['is_compatible',
                                                            'logs'],
                                              'module': 'os.unix.linux.redhat.yum',
                                              'namespace': 'yum'}},
                           'suse': {'_os': [{'class': 'SuSEPlugin',
                                             'exports': ['architecture',
                                                         'dhcp',
                                                         'dns',
                                                         'domain',
                                                         'gateway',
                                                         'get_all_records',
                                                         'hostname',
                                                         'interface',
                                                         'ips',
                                                         'netmask',
                                                         'os',
                                                         'users',
                                                         'version'],
                                             'fullname': 'dissect.target.plugins.os.unix.linux.suse._os.SuSEPlugin',
                                             'functions': ['architecture',
                                                           'dhcp',
                                                           'dns',
                                                           'domain',
                                                           'gateway',
                                                           'get_all_records',
                                                           'hostname',
                                                           'interface',
                                                           'ips',
                                                           'is_compatible',
                                                           'netmask',
                                                           'os',
                                                           'users',
                                                           'version'],
                                             'module': 'os.unix.linux.suse._os',
                                             'namespace': None}],
                                    'zypper': {'class': 'ZypperPlugin',
                                               'exports': ['logs'],
                                               'fullname': 'dissect.target.plugins.os.unix.linux.suse.zypper.ZypperPlugin',
                                               'functions': ['is_compatible',
                                                             'logs'],
                                               'module': 'os.unix.linux.suse.zypper',
                                               'namespace': 'zypper'}}},
                 'locale': {'class': 'LocalePlugin',
                            'exports': ['keyboard', 'language', 'timezone'],
                            'fullname': 'dissect.target.plugins.os.unix.locale.LocalePlugin',
                            'functions': ['is_compatible',
                                          'keyboard',
                                          'language',
                                          'timezone'],
                            'module': 'os.unix.locale',
                            'namespace': None},
                 'log': {'atop': {'class': 'AtopPlugin',
                                  'exports': ['atop'],
                                  'fullname': 'dissect.target.plugins.os.unix.log.atop.AtopPlugin',
                                  'functions': ['atop', 'is_compatible'],
                                  'module': 'os.unix.log.atop',
                                  'namespace': None},
                         'audit': {'class': 'AuditPlugin',
                                   'exports': ['audit'],
                                   'fullname': 'dissect.target.plugins.os.unix.log.audit.AuditPlugin',
                                   'functions': ['audit',
                                                 'get_log_paths',
                                                 'is_compatible'],
                                   'module': 'os.unix.log.audit',
                                   'namespace': None},
                         'auth': {'class': 'AuthPlugin',
                                  'exports': ['authlog', 'securelog'],
                                  'fullname': 'dissect.target.plugins.os.unix.log.auth.AuthPlugin',
                                  'functions': ['authlog',
                                                'is_compatible',
                                                'securelog'],
                                  'module': 'os.unix.log.auth',
                                  'namespace': None},
                         'btmp': {'class': 'BtmpPlugin',
                                  'exports': ['btmp'],
                                  'fullname': 'dissect.target.plugins.os.unix.log.btmp.BtmpPlugin',
                                  'functions': ['btmp', 'is_compatible'],
                                  'module': 'os.unix.log.btmp',
                                  'namespace': None},
                         'lastlog': {'class': 'LastLogPlugin',
                                     'exports': ['lastlog'],
                                     'fullname': 'dissect.target.plugins.os.unix.log.lastlog.LastLogPlugin',
                                     'functions': ['is_compatible', 'lastlog'],
                                     'module': 'os.unix.log.lastlog',
                                     'namespace': None},
                         'messages': {'class': 'MessagesPlugin',
                                      'exports': ['messages', 'syslog'],
                                      'fullname': 'dissect.target.plugins.os.unix.log.messages.MessagesPlugin',
                                      'functions': ['is_compatible',
                                                    'messages',
                                                    'syslog'],
                                      'module': 'os.unix.log.messages',
                                      'namespace': None},
                         'wtmp': {'class': 'WtmpPlugin',
                                  'exports': ['wtmp'],
                                  'fullname': 'dissect.target.plugins.os.unix.log.wtmp.WtmpPlugin',
                                  'functions': ['is_compatible', 'wtmp'],
                                  'module': 'os.unix.log.wtmp',
                                  'namespace': None}},
                 'packagemanager': {'class': 'PackageManagerPlugin',
                                    'exports': ['logs'],
                                    'fullname': 'dissect.target.plugins.os.unix.packagemanager.PackageManagerPlugin',
                                    'functions': ['is_compatible', 'logs'],
                                    'module': 'os.unix.packagemanager',
                                    'namespace': 'packagemanager'},
                 'services': {'class': 'ServicePlugin',
                              'exports': ['services'],
                              'fullname': 'dissect.target.plugins.os.unix.services.ServicePlugin',
                              'functions': ['is_compatible', 'services'],
                              'module': 'os.unix.services',
                              'namespace': None},
                 'shadow': {'class': 'ShadowPlugin',
                            'exports': ['passwords'],
                            'fullname': 'dissect.target.plugins.os.unix.shadow.ShadowPlugin',
                            'functions': ['is_compatible', 'passwords'],
                            'module': 'os.unix.shadow',
                            'namespace': None},
                 'ssh': {'class': 'SSHPlugin',
                         'exports': ['authorized_keys',
                                     'known_hosts',
                                     'private_keys',
                                     'public_keys'],
                         'fullname': 'dissect.target.plugins.os.unix.ssh.SSHPlugin',
                         'functions': ['authorized_keys',
                                       'is_compatible',
                                       'known_hosts',
                                       'private_keys',
                                       'public_keys'],
                         'module': 'os.unix.ssh',
                         'namespace': 'ssh'}},
        'windows': {'_os': [{'class': 'WindowsPlugin',
                             'exports': ['architecture',
                                         'get_all_records',
                                         'hostname',
                                         'ips',
                                         'os',
                                         'users',
                                         'version'],
                             'fullname': 'dissect.target.plugins.os.windows._os.WindowsPlugin',
                             'functions': ['architecture',
                                           'get_all_records',
                                           'hostname',
                                           'ips',
                                           'is_compatible',
                                           'os',
                                           'users',
                                           'version'],
                             'module': 'os.windows._os',
                             'namespace': None}],
                    'activitiescache': {'class': 'ActivitiesCachePlugin',
                                        'exports': ['activitiescache'],
                                        'fullname': 'dissect.target.plugins.os.windows.activitiescache.ActivitiesCachePlugin',
                                        'functions': ['activitiescache',
                                                      'is_compatible'],
                                        'module': 'os.windows.activitiescache',
                                        'namespace': None},
                    'adpolicy': {'class': 'ADPolicyPlugin',
                                 'exports': ['adpolicy'],
                                 'fullname': 'dissect.target.plugins.os.windows.adpolicy.ADPolicyPlugin',
                                 'functions': ['adpolicy', 'is_compatible'],
                                 'module': 'os.windows.adpolicy',
                                 'namespace': None},
                    'amcache': {'class': 'AmcachePlugin',
                                'exports': ['applaunches',
                                            'application_files',
                                            'applications',
                                            'device_containers',
                                            'drivers',
                                            'files',
                                            'programs',
                                            'shortcuts'],
                                'fullname': 'dissect.target.plugins.os.windows.amcache.AmcachePlugin',
                                'functions': ['applaunches',
                                              'application_files',
                                              'applications',
                                              'device_containers',
                                              'drivers',
                                              'files',
                                              'is_compatible',
                                              'programs',
                                              'shortcuts'],
                                'module': 'os.windows.amcache',
                                'namespace': 'amcache'},
                    'catroot': {'class': 'CatrootPlugin',
                                'exports': ['catroot'],
                                'fullname': 'dissect.target.plugins.os.windows.catroot.CatrootPlugin',
                                'functions': ['catroot', 'is_compatible'],
                                'module': 'os.windows.catroot',
                                'namespace': None},
                    'cim': {'class': 'CimPlugin',
                            'exports': ['consumerbindings'],
                            'fullname': 'dissect.target.plugins.os.windows.cim.CimPlugin',
                            'functions': ['consumerbindings',
                                          'is_compatible',
                                          'repo'],
                            'module': 'os.windows.cim',
                            'namespace': 'cim'},
                    'clfs': {'class': 'ClfsPlugin',
                             'exports': ['clfs'],
                             'fullname': 'dissect.target.plugins.os.windows.clfs.ClfsPlugin',
                             'functions': ['clfs', 'is_compatible'],
                             'module': 'os.windows.clfs',
                             'namespace': None},
                    'datetime': {'class': 'DateTimePlugin',
                                 'exports': [],
                                 'fullname': 'dissect.target.plugins.os.windows.datetime.DateTimePlugin',
                                 'functions': ['is_compatible',
                                               'local',
                                               'to_utc',
                                               'tz',
                                               'tzinfo'],
                                 'module': 'os.windows.datetime',
                                 'namespace': 'datetime'},
                    'defender': {'class': 'MicrosoftDefenderPlugin',
                                 'exports': ['evtx', 'quarantine', 'recover'],
                                 'fullname': 'dissect.target.plugins.os.windows.defender.MicrosoftDefenderPlugin',
                                 'functions': ['evtx',
                                               'is_compatible',
                                               'quarantine',
                                               'recover'],
                                 'module': 'os.windows.defender',
                                 'namespace': 'defender'},
                    'env': {'class': 'EnvironmentVariablePlugin',
                            'exports': ['environment_variables',
                                        'path_extensions'],
                            'fullname': 'dissect.target.plugins.os.windows.env.EnvironmentVariablePlugin',
                            'functions': ['env',
                                          'environment_variables',
                                          'expand_env',
                                          'is_compatible',
                                          'path_extensions',
                                          'pathext',
                                          'user_env'],
                            'module': 'os.windows.env',
                            'namespace': None},
                    'exchange': {'exchange': {'class': 'ExchangePlugin',
                                              'exports': ['transport_agents'],
                                              'fullname': 'dissect.target.plugins.os.windows.exchange.exchange.ExchangePlugin',
                                              'functions': ['is_compatible',
                                                            'transport_agents'],
                                              'module': 'os.windows.exchange.exchange',
                                              'namespace': 'exchange'}},
                    'generic': {'class': 'GenericPlugin',
                                'exports': ['activity',
                                            'alternateshell',
                                            'appinit',
                                            'bootshell',
                                            'codepage',
                                            'commandprocautorun',
                                            'domain',
                                            'filerenameop',
                                            'install_date',
                                            'knowndlls',
                                            'ndis',
                                            'ntversion',
                                            'nullsessionpipes',
                                            'pathenvironment',
                                            'sessionmanager',
                                            'winrar',
                                            'winsocknamespaceprovider'],
                                'fullname': 'dissect.target.plugins.os.windows.generic.GenericPlugin',
                                'functions': ['activity',
                                              'alternateshell',
                                              'appinit',
                                              'bootshell',
                                              'codepage',
                                              'commandprocautorun',
                                              'domain',
                                              'filerenameop',
                                              'install_date',
                                              'is_compatible',
                                              'knowndlls',
                                              'ndis',
                                              'ntversion',
                                              'nullsessionpipes',
                                              'pathenvironment',
                                              'sessionmanager',
                                              'winrar',
                                              'winsocknamespaceprovider'],
                                'module': 'os.windows.generic',
                                'namespace': None},
                    'lnk': {'class': 'LnkPlugin',
                            'exports': ['lnk'],
                            'fullname': 'dissect.target.plugins.os.windows.lnk.LnkPlugin',
                            'functions': ['is_compatible', 'lnk'],
                            'module': 'os.windows.lnk',
                            'namespace': None},
                    'locale': {'class': 'LocalePlugin',
                               'exports': ['keyboard', 'language', 'timezone'],
                               'fullname': 'dissect.target.plugins.os.windows.locale.LocalePlugin',
                               'functions': ['is_compatible',
                                             'keyboard',
                                             'language',
                                             'timezone'],
                               'module': 'os.windows.locale',
                               'namespace': None},
                    'log': {'amcache': {'class': 'AmcacheInstallPlugin',
                                        'exports': ['amcache_install'],
                                        'fullname': 'dissect.target.plugins.os.windows.log.amcache.AmcacheInstallPlugin',
                                        'functions': ['amcache_install',
                                                      'is_compatible'],
                                        'module': 'os.windows.log.amcache',
                                        'namespace': None},
                            'etl': {'class': 'EtlPlugin',
                                    'exports': ['boot', 'etl', 'shutdown'],
                                    'fullname': 'dissect.target.plugins.os.windows.log.etl.EtlPlugin',
                                    'functions': ['boot',
                                                  'etl',
                                                  'is_compatible',
                                                  'shutdown'],
                                    'module': 'os.windows.log.etl',
                                    'namespace': 'etl'},
                            'evt': {'class': 'EvtPlugin',
                                    'exports': ['evt', 'scraped_evt'],
                                    'fullname': 'dissect.target.plugins.os.windows.log.evt.EvtPlugin',
                                    'functions': ['evt',
                                                  'get_logs',
                                                  'get_logs_from_dir',
                                                  'get_logs_from_registry',
                                                  'is_compatible',
                                                  'scraped_evt'],
                                    'module': 'os.windows.log.evt',
                                    'namespace': None},
                            'evtx': {'class': 'EvtxPlugin',
                                     'exports': ['evtx', 'scraped_evtx'],
                                     'fullname': 'dissect.target.plugins.os.windows.log.evtx.EvtxPlugin',
                                     'functions': ['evtx',
                                                   'get_logs',
                                                   'get_logs_from_dir',
                                                   'get_logs_from_registry',
                                                   'is_compatible',
                                                   'scraped_evtx'],
                                     'module': 'os.windows.log.evtx',
                                     'namespace': None},
                            'pfro': {'class': 'PfroPlugin',
                                     'exports': ['pfro'],
                                     'fullname': 'dissect.target.plugins.os.windows.log.pfro.PfroPlugin',
                                     'functions': ['is_compatible', 'pfro'],
                                     'module': 'os.windows.log.pfro',
                                     'namespace': None}},
                    'notifications': {'class': 'NotificationsPlugin',
                                      'exports': ['wpndatabase'],
                                      'fullname': 'dissect.target.plugins.os.windows.notifications.NotificationsPlugin',
                                      'functions': ['is_compatible',
                                                    'wpndatabase'],
                                      'module': 'os.windows.notifications',
                                      'namespace': 'notifications'},
                    'powershell': {'class': 'PowerShellHistoryPlugin',
                                   'exports': ['powershell_history'],
                                   'fullname': 'dissect.target.plugins.os.windows.powershell.PowerShellHistoryPlugin',
                                   'functions': ['is_compatible',
                                                 'powershell_history'],
                                   'module': 'os.windows.powershell',
                                   'namespace': None},
                    'prefetch': {'class': 'PrefetchPlugin',
                                 'exports': ['prefetch'],
                                 'fullname': 'dissect.target.plugins.os.windows.prefetch.PrefetchPlugin',
                                 'functions': ['is_compatible', 'prefetch'],
                                 'module': 'os.windows.prefetch',
                                 'namespace': None},
                    'recyclebin': {'class': 'RecyclebinPlugin',
                                   'exports': ['recyclebin'],
                                   'fullname': 'dissect.target.plugins.os.windows.recyclebin.RecyclebinPlugin',
                                   'functions': ['is_compatible', 'recyclebin'],
                                   'module': 'os.windows.recyclebin',
                                   'namespace': None},
                    'regf': {'7zip': {'class': 'SevenZipPlugin',
                                      'exports': ['sevenzip'],
                                      'fullname': 'dissect.target.plugins.os.windows.regf.7zip.SevenZipPlugin',
                                      'functions': ['is_compatible',
                                                    'sevenzip'],
                                      'module': 'os.windows.regf.7zip',
                                      'namespace': None},
                             'auditpol': {'class': 'AuditpolPlugin',
                                          'exports': ['auditpol'],
                                          'fullname': 'dissect.target.plugins.os.windows.regf.auditpol.AuditpolPlugin',
                                          'functions': ['auditpol',
                                                        'is_compatible'],
                                          'module': 'os.windows.regf.auditpol',
                                          'namespace': None},
                             'bam': {'class': 'BamDamPlugin',
                                     'exports': ['bam'],
                                     'fullname': 'dissect.target.plugins.os.windows.regf.bam.BamDamPlugin',
                                     'functions': ['bam', 'is_compatible'],
                                     'module': 'os.windows.regf.bam',
                                     'namespace': None},
                             'cit': {'class': 'CITPlugin',
                                     'exports': ['cit',
                                                 'dp',
                                                 'modules',
                                                 'puu',
                                                 'telemetry'],
                                     'fullname': 'dissect.target.plugins.os.windows.regf.cit.CITPlugin',
                                     'functions': ['cit',
                                                   'dp',
                                                   'is_compatible',
                                                   'modules',
                                                   'puu',
                                                   'telemetry'],
                                     'module': 'os.windows.regf.cit',
                                     'namespace': 'cit'},
                             'clsid': {'class': 'CLSIDPlugin',
                                       'exports': ['machine', 'user'],
                                       'fullname': 'dissect.target.plugins.os.windows.regf.clsid.CLSIDPlugin',
                                       'functions': ['is_compatible',
                                                     'machine',
                                                     'user'],
                                       'module': 'os.windows.regf.clsid',
                                       'namespace': 'clsid'},
                             'firewall': {'class': 'FirewallPlugin',
                                          'exports': ['firewall'],
                                          'fullname': 'dissect.target.plugins.os.windows.regf.firewall.FirewallPlugin',
                                          'functions': ['firewall',
                                                        'is_compatible'],
                                          'module': 'os.windows.regf.firewall',
                                          'namespace': None},
                             'mru': {'class': 'MRUPlugin',
                                     'exports': ['acmru',
                                                 'lastvisited',
                                                 'msoffice',
                                                 'mstsc',
                                                 'networkdrive',
                                                 'opensave',
                                                 'recentdocs',
                                                 'run'],
                                     'fullname': 'dissect.target.plugins.os.windows.regf.mru.MRUPlugin',
                                     'functions': ['acmru',
                                                   'is_compatible',
                                                   'lastvisited',
                                                   'msoffice',
                                                   'mstsc',
                                                   'networkdrive',
                                                   'opensave',
                                                   'recentdocs',
                                                   'run'],
                                     'module': 'os.windows.regf.mru',
                                     'namespace': 'mru'},
                             'muicache': {'class': 'MuiCachePlugin',
                                          'exports': ['muicache'],
                                          'fullname': 'dissect.target.plugins.os.windows.regf.muicache.MuiCachePlugin',
                                          'functions': ['is_compatible',
                                                        'muicache'],
                                          'module': 'os.windows.regf.muicache',
                                          'namespace': None},
                             'nethist': {'class': 'NethistPlugin',
                                         'exports': ['network_history'],
                                         'fullname': 'dissect.target.plugins.os.windows.regf.nethist.NethistPlugin',
                                         'functions': ['is_compatible',
                                                       'network_history'],
                                         'module': 'os.windows.regf.nethist',
                                         'namespace': None},
                             'recentfilecache': {'class': 'RecentFileCachePlugin',
                                                 'exports': ['recentfilecache'],
                                                 'fullname': 'dissect.target.plugins.os.windows.regf.recentfilecache.RecentFileCachePlugin',
                                                 'functions': ['is_compatible',
                                                               'recentfilecache'],
                                                 'module': 'os.windows.regf.recentfilecache',
                                                 'namespace': None},
                             'regf': {'class': 'RegfPlugin',
                                      'exports': ['regf'],
                                      'fullname': 'dissect.target.plugins.os.windows.regf.regf.RegfPlugin',
                                      'functions': ['is_compatible', 'regf'],
                                      'module': 'os.windows.regf.regf',
                                      'namespace': None},
                             'runkeys': {'class': 'RunKeysPlugin',
                                         'exports': ['runkeys'],
                                         'fullname': 'dissect.target.plugins.os.windows.regf.runkeys.RunKeysPlugin',
                                         'functions': ['is_compatible',
                                                       'runkeys'],
                                         'module': 'os.windows.regf.runkeys',
                                         'namespace': None},
                             'shellbags': {'class': 'ShellBagsPlugin',
                                           'exports': ['shellbags'],
                                           'fullname': 'dissect.target.plugins.os.windows.regf.shellbags.ShellBagsPlugin',
                                           'functions': ['is_compatible',
                                                         'shellbags'],
                                           'module': 'os.windows.regf.shellbags',
                                           'namespace': None},
                             'shimcache': {'class': 'ShimcachePlugin',
                                           'exports': ['shimcache'],
                                           'fullname': 'dissect.target.plugins.os.windows.regf.shimcache.ShimcachePlugin',
                                           'functions': ['is_compatible',
                                                         'shimcache'],
                                           'module': 'os.windows.regf.shimcache',
                                           'namespace': None},
                             'trusteddocs': {'class': 'TrustedDocumentsPlugin',
                                             'exports': ['trusteddocs'],
                                             'fullname': 'dissect.target.plugins.os.windows.regf.trusteddocs.TrustedDocumentsPlugin',
                                             'functions': ['is_compatible',
                                                           'trusteddocs'],
                                             'module': 'os.windows.regf.trusteddocs',
                                             'namespace': None},
                             'usb': {'class': 'UsbPlugin',
                                     'exports': ['usb'],
                                     'fullname': 'dissect.target.plugins.os.windows.regf.usb.UsbPlugin',
                                     'functions': ['is_compatible',
                                                   'parse_device_name',
                                                   'unpack_timestamps',
                                                   'usb'],
                                     'module': 'os.windows.regf.usb',
                                     'namespace': None},
                             'userassist': {'class': 'UserAssistPlugin',
                                            'exports': ['userassist'],
                                            'fullname': 'dissect.target.plugins.os.windows.regf.userassist.UserAssistPlugin',
                                            'functions': ['is_compatible',
                                                          'userassist'],
                                            'module': 'os.windows.regf.userassist',
                                            'namespace': None}},
                    'registry': {'class': 'RegistryPlugin',
                                 'exports': [],
                                 'fullname': 'dissect.target.plugins.os.windows.registry.RegistryPlugin',
                                 'functions': ['add_hive',
                                               'get_user',
                                               'get_user_details',
                                               'is_compatible',
                                               'iterhives',
                                               'iterkeys',
                                               'key',
                                               'keys',
                                               'load_user_hives',
                                               'map_hive',
                                               'mappings',
                                               'root',
                                               'subkey',
                                               'value'],
                                 'module': 'os.windows.registry',
                                 'namespace': 'registry'},
                    'sam': {'class': 'SamPlugin',
                            'exports': ['sam'],
                            'fullname': 'dissect.target.plugins.os.windows.sam.SamPlugin',
                            'functions': ['is_compatible', 'sam'],
                            'module': 'os.windows.sam',
                            'namespace': None},
                    'services': {'class': 'ServicesPlugin',
                                 'exports': ['services'],
                                 'fullname': 'dissect.target.plugins.os.windows.services.ServicesPlugin',
                                 'functions': ['is_compatible', 'services'],
                                 'module': 'os.windows.services',
                                 'namespace': None},
                    'sru': {'class': 'SRUPlugin',
                            'exports': ['application',
                                        'application_timeline',
                                        'energy_estimator',
                                        'energy_usage',
                                        'energy_usage_lt',
                                        'network_connectivity',
                                        'network_data',
                                        'push_notification',
                                        'sdp_cpu_provider',
                                        'sdp_network_provider',
                                        'sdp_physical_disk_provider',
                                        'sdp_volume_provider',
                                        'vfu'],
                            'fullname': 'dissect.target.plugins.os.windows.sru.SRUPlugin',
                            'functions': ['application',
                                          'application_timeline',
                                          'energy_estimator',
                                          'energy_usage',
                                          'energy_usage_lt',
                                          'is_compatible',
                                          'network_connectivity',
                                          'network_data',
                                          'push_notification',
                                          'sdp_cpu_provider',
                                          'sdp_network_provider',
                                          'sdp_physical_disk_provider',
                                          'sdp_volume_provider',
                                          'vfu'],
                            'module': 'os.windows.sru',
                            'namespace': 'sru'},
                    'startupinfo': {'class': 'StartupInfoPlugin',
                                    'exports': ['startupinfo'],
                                    'fullname': 'dissect.target.plugins.os.windows.startupinfo.StartupInfoPlugin',
                                    'functions': ['is_compatible',
                                                  'startupinfo'],
                                    'module': 'os.windows.startupinfo',
                                    'namespace': None},
                    'syscache': {'class': 'SyscachePlugin',
                                 'exports': ['syscache'],
                                 'fullname': 'dissect.target.plugins.os.windows.syscache.SyscachePlugin',
                                 'functions': ['is_compatible', 'syscache'],
                                 'module': 'os.windows.syscache',
                                 'namespace': None},
                    'tasks': {'class': 'TasksPlugin',
                              'exports': ['tasks'],
                              'fullname': 'dissect.target.plugins.os.windows.tasks.TasksPlugin',
                              'functions': ['is_compatible', 'tasks'],
                              'module': 'os.windows.tasks',
                              'namespace': None},
                    'thumbcache': {'class': 'ThumbcachePlugin',
                                   'exports': ['iconcache', 'thumbcache'],
                                   'fullname': 'dissect.target.plugins.os.windows.thumbcache.ThumbcachePlugin',
                                   'functions': ['iconcache',
                                                 'is_compatible',
                                                 'thumbcache'],
                                   'module': 'os.windows.thumbcache',
                                   'namespace': 'thumbcache'},
                    'ual': {'class': 'UalPlugin',
                            'exports': ['client_access',
                                        'domains_seen',
                                        'role_access',
                                        'system_identities',
                                        'virtual_machines'],
                            'fullname': 'dissect.target.plugins.os.windows.ual.UalPlugin',
                            'functions': ['client_access',
                                          'domains_seen',
                                          'is_compatible',
                                          'role_access',
                                          'system_identities',
                                          'virtual_machines'],
                            'module': 'os.windows.ual',
                            'namespace': 'ual'},
                    'wer': {'class': 'WindowsErrorReportingPlugin',
                            'exports': ['wer'],
                            'fullname': 'dissect.target.plugins.os.windows.wer.WindowsErrorReportingPlugin',
                            'functions': ['is_compatible', 'wer'],
                            'module': 'os.windows.wer',
                            'namespace': None}}}}
